"""Diese Datei ist auto-generiert! Siehe ressourcen/generate_enums.py im git repo! """

from enum import Enum
from typing import Optional

from st_minecraft.en.entity import EntityCollection as _Collection


class EntitySammlung(Enum):

    @staticmethod
    def von_englisch(e: _Collection) -> Optional["EntitySammlung"]:
        try:
            return EntitySammlung._value2member_map_[e.value]
        except KeyError:
            return None

    def zu_englisch(self) -> Optional[_Collection]:
        try:
            return _Collection._value2member_map_[self.value]
        except KeyError:
            return None

    Gegenstand = "ITEM"
    Erfahrungskugel = "EXPERIENCE_ORB"
    Partikelwolke = "AREA_EFFECT_CLOUD"
    Großwächter = "ELDER_GUARDIAN"
    Wither_Skelett = "WITHER_SKELETON"
    Eiswanderer = "STRAY"
    Geworfenes_Ei = "EGG"
    Leinenknoten = "LEASH_KNOT"
    Gemälde = "PAINTING"
    Pfeil = "ARROW"
    Schneeball = "SNOWBALL"
    Feuerkugel = "FIREBALL"
    Kleine_Feuerkugel = "SMALL_FIREBALL"
    Geworfene_Enderperle = "ENDER_PEARL"
    Enderauge = "EYE_OF_ENDER"
    Wurftrank = "SPLASH_POTION"
    Verweiltrank = "LINGERING_POTION"
    Geworfenes_Erfahrungsfläschchen = "EXPERIENCE_BOTTLE"
    Rahmen = "ITEM_FRAME"
    Wither_Schädel = "WITHER_SKULL"
    Gezündetes_TNT = "TNT"
    Fallender_Block = "FALLING_BLOCK"
    Feuerwerksrakete = "FIREWORK_ROCKET"
    Wüstenzombie = "HUSK"
    Spektralpfeil = "SPECTRAL_ARROW"
    Shulker_Geschoss = "SHULKER_BULLET"
    Drachen_Feuerkugel = "DRAGON_FIREBALL"
    Zombiedorfbewohner = "ZOMBIE_VILLAGER"
    Skelettpferd = "SKELETON_HORSE"
    Zombiepferd = "ZOMBIE_HORSE"
    Rüstungsständer = "ARMOR_STAND"
    Esel = "DONKEY"
    Maultier = "MULE"
    Fangzähne = "EVOKER_FANGS"
    Magier = "EVOKER"
    Plagegeist = "VEX"
    Diener = "VINDICATOR"
    Illusionist = "ILLUSIONER"
    Befehlsblocklore = "COMMAND_BLOCK_MINECART"
    Lore = "MINECART"
    Güterlore = "CHEST_MINECART"
    Antriebslore = "FURNACE_MINECART"
    TNT_Lore = "TNT_MINECART"
    Trichterlore = "HOPPER_MINECART"
    Spawner_Lore = "SPAWNER_MINECART"
    Creeper = "CREEPER"
    Skelett = "SKELETON"
    Spinne = "SPIDER"
    Riese = "GIANT"
    Zombie = "ZOMBIE"
    Schleim = "SLIME"
    Ghast = "GHAST"
    Zombifizierter_Piglin = "ZOMBIFIED_PIGLIN"
    Enderman = "ENDERMAN"
    Höhlenspinne = "CAVE_SPIDER"
    Silberfischchen = "SILVERFISH"
    Lohe = "BLAZE"
    Magmawürfel = "MAGMA_CUBE"
    Enderdrache = "ENDER_DRAGON"
    Wither = "WITHER"
    Fledermaus = "BAT"
    Hexe = "WITCH"
    Endermite = "ENDERMITE"
    Wächter = "GUARDIAN"
    Shulker = "SHULKER"
    Schwein = "PIG"
    Schaf = "SHEEP"
    Kuh = "COW"
    Huhn = "CHICKEN"
    Tintenfisch = "SQUID"
    Wolf = "WOLF"
    Mooshroom = "MOOSHROOM"
    Schneegolem = "SNOW_GOLEM"
    Ozelot = "OCELOT"
    Eisengolem = "IRON_GOLEM"
    Pferd = "HORSE"
    Kaninchen = "RABBIT"
    Eisbär = "POLAR_BEAR"
    Lama = "LLAMA"
    Lamaspucke = "LLAMA_SPIT"
    Papagei = "PARROT"
    Dorfbewohner = "VILLAGER"
    Enderkristall = "END_CRYSTAL"
    Schildkröte = "TURTLE"
    Phantom = "PHANTOM"
    Dreizack = "TRIDENT"
    Kabeljau = "COD"
    Lachs = "SALMON"
    Kugelfisch = "PUFFERFISH"
    Tropenfisch = "TROPICAL_FISH"
    Ertrunkener = "DROWNED"
    Delfin = "DOLPHIN"
    Katze = "CAT"
    Panda = "PANDA"
    Plünderer = "PILLAGER"
    Verwüster = "RAVAGER"
    Händlerlama = "TRADER_LLAMA"
    Fahrender_Händler = "WANDERING_TRADER"
    Fuchs = "FOX"
    Biene = "BEE"
    Hoglin = "HOGLIN"
    Piglin = "PIGLIN"
    Schreiter = "STRIDER"
    Zoglin = "ZOGLIN"
    Piglin_Barbar = "PIGLIN_BRUTE"
    Axolotl = "AXOLOTL"
    Leuchtrahmen = "GLOW_ITEM_FRAME"
    Leuchttintenfisch = "GLOW_SQUID"
    Ziege = "GOAT"
    Marker = "MARKER"
    Hilfsgeist = "ALLAY"
    Frosch = "FROG"
    Kaulquappe = "TADPOLE"
    Wärter = "WARDEN"
    Dromedar = "CAMEL"
    Blockdarsteller = "BLOCK_DISPLAY"
    Interaktionsobjekt = "INTERACTION"
    Gegenstandsdarsteller = "ITEM_DISPLAY"
    Schnüffler = "SNIFFER"
    Textdarsteller = "TEXT_DISPLAY"
    Böe = "BREEZE"
    Windkugel = "WIND_CHARGE"
    Windkugel__BREEZE_WIND_CHARGE = "BREEZE_WIND_CHARGE"
    Gürteltier = "ARMADILLO"
    Sumpfskelett = "BOGGED"
    Unheilvoller_Gegenstands_Spawner = "OMINOUS_ITEM_SPAWNER"
    Akazienholzboot = "ACACIA_BOAT"
    Akazienholztruhenboot = "ACACIA_CHEST_BOAT"
    Bambusfloß = "BAMBOO_RAFT"
    Bambus_Truhenfloß = "BAMBOO_CHEST_RAFT"
    Birkenholzboot = "BIRCH_BOAT"
    Birkenholztruhenboot = "BIRCH_CHEST_BOAT"
    Kirschholzboot = "CHERRY_BOAT"
    Kirschholztruhenboot = "CHERRY_CHEST_BOAT"
    Schwarzeichenholzboot = "DARK_OAK_BOAT"
    Schwarzeichenholztruhenboot = "DARK_OAK_CHEST_BOAT"
    Tropenholzboot = "JUNGLE_BOAT"
    Tropenholztruhenboot = "JUNGLE_CHEST_BOAT"
    Mangrovenholzboot = "MANGROVE_BOAT"
    Mangrovenholztruhenboot = "MANGROVE_CHEST_BOAT"
    Eichenholzboot = "OAK_BOAT"
    Eichenholztruhenboot = "OAK_CHEST_BOAT"
    Blasseichenholzboot = "PALE_OAK_BOAT"
    Blasseichenholztruhenboot = "PALE_OAK_CHEST_BOAT"
    Fichtenholzboot = "SPRUCE_BOAT"
    Fichtenholztruhenboot = "SPRUCE_CHEST_BOAT"
    Knarz = "CREAKING"
    Schwimmer = "FISHING_BOBBER"
    Blitz = "LIGHTNING_BOLT"
    Spieler = "PLAYER"
