"""Diese Datei ist auto-generiert! Siehe ressourcen/generate_enums.py im git repo! """

from enum import Enum
from typing import Optional

from st_minecraft.en.entity import EntityCollection as _Collection


class EntitySammlung(Enum):

    @staticmethod
    def von_englisch(e: _Collection) -> Optional["EntitySammlung"]:
        try:
            return EntitySammlung._value2member_map_[e.value]
        except KeyError:
            return None

    def zu_englisch(self) -> Optional[_Collection]:
        try:
            return EntitySammlung._value2member_map_[self.value]
        except KeyError:
            return None

    Hilfsgeist = "ALLAY"
    Partikelwolke = "AREA_EFFECT_CLOUD"
    Rüstungsständer = "ARMOR_STAND"
    Pfeil = "ARROW"
    Axolotl = "AXOLOTL"
    Fledermaus = "BAT"
    Biene = "BEE"
    Lohe = "BLAZE"
    Blockdarsteller = "BLOCK_DISPLAY"
    Boot = "BOAT"
    Dromedar = "CAMEL"
    Katze = "CAT"
    Höhlenspinne = "CAVE_SPIDER"
    Truhenboot = "CHEST_BOAT"
    Güterlore = "CHEST_MINECART"
    Huhn = "CHICKEN"
    Kabeljau = "COD"
    Befehlsblocklore = "COMMAND_BLOCK_MINECART"
    Kuh = "COW"
    Creeper = "CREEPER"
    Delfin = "DOLPHIN"
    Esel = "DONKEY"
    Drachen_Feuerkugel = "DRAGON_FIREBALL"
    Ertrunkener = "DROWNED"
    Geworfenes_Ei = "EGG"
    Großer_Wächter = "ELDER_GUARDIAN"
    Enderkristall = "END_CRYSTAL"
    Enderdrache = "ENDER_DRAGON"
    Geworfene_Enderperle = "ENDER_PEARL"
    Enderman = "ENDERMAN"
    Endermite = "ENDERMITE"
    Magier = "EVOKER"
    Fangzähne = "EVOKER_FANGS"
    Geworfenes_Erfahrungsfläschchen = "EXPERIENCE_BOTTLE"
    Erfahrungskugel = "EXPERIENCE_ORB"
    Enderauge = "EYE_OF_ENDER"
    Fallender_Block = "FALLING_BLOCK"
    Feuerkugel = "FIREBALL"
    Feuerwerksrakete = "FIREWORK_ROCKET"
    Schwimmer = "FISHING_BOBBER"
    Fuchs = "FOX"
    Frosch = "FROG"
    Ofenlore = "FURNACE_MINECART"
    Ghast = "GHAST"
    Riese = "GIANT"
    Leuchtrahmen = "GLOW_ITEM_FRAME"
    Leuchttintenfisch = "GLOW_SQUID"
    Ziege = "GOAT"
    Wächter = "GUARDIAN"
    Hoglin = "HOGLIN"
    Trichterlore = "HOPPER_MINECART"
    Pferd = "HORSE"
    Wüstenzombie = "HUSK"
    Illusionist = "ILLUSIONER"
    Interagierer = "INTERACTION"
    Eisengolem = "IRON_GOLEM"
    Gegenstand = "ITEM"
    Gegenstandsdarsteller = "ITEM_DISPLAY"
    Rahmen = "ITEM_FRAME"
    Das_Killer_Kaninchen = "KILLER_BUNNY"
    Leinenknoten = "LEASH_KNOT"
    Blitz = "LIGHTNING_BOLT"
    Lama = "LLAMA"
    Lamaspucke = "LLAMA_SPIT"
    Magmawürfel = "MAGMA_CUBE"
    Marker = "MARKER"
    Lore = "MINECART"
    Mooshroom = "MOOSHROOM"
    Maultier = "MULE"
    Ozelot = "OCELOT"
    Gemälde = "PAINTING"
    Panda = "PANDA"
    Papagei = "PARROT"
    Phantom = "PHANTOM"
    Schwein = "PIG"
    Piglin = "PIGLIN"
    Piglin_Barbar = "PIGLIN_BRUTE"
    Plünderer = "PILLAGER"
    Spieler = "PLAYER"
    Eisbär = "POLAR_BEAR"
    Trank = "POTION"
    Kugelfisch = "PUFFERFISH"
    Kaninchen = "RABBIT"
    Verwüster = "RAVAGER"
    Lachs = "SALMON"
    Schaf = "SHEEP"
    Shulker = "SHULKER"
    Shulker_Geschoss = "SHULKER_BULLET"
    Silberfischchen = "SILVERFISH"
    Skelett = "SKELETON"
    Skelettpferd = "SKELETON_HORSE"
    Schleim = "SLIME"
    Kleine_Feuerkugel = "SMALL_FIREBALL"
    Schnüffler = "SNIFFER"
    Schneegolem = "SNOW_GOLEM"
    Schneeball = "SNOWBALL"
    Spawner_Lore = "SPAWNER_MINECART"
    Spektralpfeil = "SPECTRAL_ARROW"
    Spinne = "SPIDER"
    Tintenfisch = "SQUID"
    Eiswanderer = "STRAY"
    Schreiter = "STRIDER"
    Kaulquappe = "TADPOLE"
    Textdarsteller = "TEXT_DISPLAY"
    Gezündetes_TNT = "TNT"
    TNT_Lore = "TNT_MINECART"
    Händlerlama = "TRADER_LLAMA"
    Dreizack = "TRIDENT"
    Tropenfisch = "TROPICAL_FISH"
    Schildkröte = "TURTLE"
    Plagegeist = "VEX"
    Dorfbewohner = "VILLAGER"
    Diener = "VINDICATOR"
    Fahrender_Händler = "WANDERING_TRADER"
    Wärter = "WARDEN"
    Hexe = "WITCH"
    Wither = "WITHER"
    Witherskelett = "WITHER_SKELETON"
    Witherschädel = "WITHER_SKULL"
    Wolf = "WOLF"
    Zoglin = "ZOGLIN"
    Zombie = "ZOMBIE"
    Zombiepferd = "ZOMBIE_HORSE"
    Zombiedorfbewohner = "ZOMBIE_VILLAGER"
    Zombifizierter_Piglin = "ZOMBIFIED_PIGLIN"
